services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/home/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "nico"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - /mongo-data:/data/db
